---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu
    driver:
      box: chavo1/nginx64
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
